### PR TITLE
Fix withdrawal typo

### PR DESCRIPTION
**Pull request by rodkisten**
Withdrawal. ;)

### CODE REVIEW

**Comment by rodkisten** [comment]
# GENTE, EU TÔ MUITO ERRADO. É WITHDRAWL MESMO 😭

**Comment by rodkisten** [comment]
# WITHDRAWAL É ABSTINÊCIA. #cry

**Comment by rodkisten** [comment]
PERA: https://www.investopedia.com/terms/w/withdrawal.asp

**Comment by rodkisten** [comment]
http://www.uandblog.com/How-to-withdraw-money-from-ATM-machine-7steps

**Comment by rodkisten** [comment]
# ACHO QUE AMBOS ESTÃO CERTOS. :rindo-de-nervouso:

**Review by ketemartinsrufino — APPROVED** [review]

**Review by chagasaway — APPROVED** [review]

**Pull request merged**
